'use client'

import { Brain, Copy, Check, Share2, Sparkles } from 'lucide-react'
import { useState } from 'react'

interface AnalysisResultProps {
  result: string
}

export default function AnalysisResult({ result }: AnalysisResultProps) {
  const [copied, setCopied] = useState(false)

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(result)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy text: ', err)
    }
  }

  const shareResult = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Repostly.ai Analysis',
          text: result,
          url: window.location.href,
        })
      } catch (err) {
        console.error('Error sharing:', err)
      }
    } else {
      // Fallback to copying to clipboard
      copyToClipboard()
    }
  }

  return (
    <div className="space-y-10 animate-fade-in">
      <div className="text-center">
        <div className="flex items-center justify-center mb-6">
          <div className="w-16 h-16 bg-gradient-to-br from-green-100 to-blue-100 rounded-3xl flex items-center justify-center mr-4">
            <Sparkles className="h-8 w-8 text-green-600" />
          </div>
        </div>
        <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
          Analysis Complete
        </h2>
        <p className="text-xl text-gray-600 max-w-2xl mx-auto">
          Here's what the repost reveals about the person's emotional and psychological state
        </p>
      </div>

      <div className="bg-white rounded-3xl shadow-2xl border border-gray-100 p-10 relative overflow-hidden">
        {/* Background decoration */}
        <div className="absolute top-0 right-0 w-40 h-40 bg-gradient-to-br from-green-50 to-blue-50 rounded-full -translate-y-20 translate-x-20 opacity-30"></div>
        <div className="absolute bottom-0 left-0 w-32 h-32 bg-gradient-to-tr from-blue-50 to-purple-50 rounded-full translate-y-16 -translate-x-16 opacity-30"></div>
        
        <div className="flex items-center justify-between mb-10 relative z-10">
          <div className="flex items-center space-x-6">
            <div className="w-16 h-16 bg-gradient-to-br from-blue-100 to-purple-100 rounded-3xl flex items-center justify-center">
              <Brain className="h-8 w-8 text-blue-600" />
            </div>
            <div>
              <h3 className="text-3xl font-bold text-gray-900">Psychological Analysis</h3>
              <p className="text-gray-500 text-lg">AI-generated insights</p>
            </div>
          </div>
          
          <div className="flex items-center space-x-4">
            <button
              onClick={copyToClipboard}
              className="p-4 text-gray-500 hover:text-blue-600 hover:bg-blue-50 rounded-2xl transition-all duration-300 group"
              title="Copy analysis"
            >
              {copied ? (
                <Check className="h-6 w-6 text-green-600" />
              ) : (
                <Copy className="h-6 w-6 group-hover:scale-110 transition-transform duration-200" />
              )}
            </button>
            <button
              onClick={shareResult}
              className="p-4 text-gray-500 hover:text-blue-600 hover:bg-blue-50 rounded-2xl transition-all duration-300 group"
              title="Share analysis"
            >
              <Share2 className="h-6 w-6 group-hover:scale-110 transition-transform duration-200" />
            </button>
          </div>
        </div>

        <div className="bg-gradient-to-r from-gray-50 to-blue-50 rounded-3xl p-10 border-l-4 border-blue-500 relative z-10">
          {result.split('\n').map((paragraph, index) => (
            <p key={index} className="text-gray-800 leading-relaxed mb-6 last:mb-0 text-lg">
              {paragraph}
            </p>
          ))}
        </div>

        <div className="mt-10 p-8 bg-gradient-to-r from-yellow-50 to-orange-50 rounded-3xl border border-yellow-200 relative z-10">
          <div className="flex items-start space-x-6">
            <div className="w-12 h-12 bg-yellow-100 rounded-2xl flex items-center justify-center flex-shrink-0">
              <Sparkles className="h-6 w-6 text-yellow-600" />
            </div>
            <div>
              <p className="text-yellow-800 font-semibold text-lg mb-2">Important Disclaimer</p>
              <p className="text-yellow-700 leading-relaxed">
                This analysis is generated by AI for entertainment purposes only. 
                It should not be considered professional psychological advice or used to make assumptions about anyone's mental health.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="text-center">
        <button
          onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
          className="group bg-white border-2 border-gray-200 hover:border-blue-300 text-gray-700 font-bold py-5 px-10 rounded-2xl shadow-lg hover:shadow-xl transform hover:scale-105 transition-all duration-300 text-lg"
        >
          <span className="flex items-center">
            <Sparkles className="h-5 w-5 mr-3 group-hover:rotate-12 transition-transform duration-200" />
            Analyze Another Repost
          </span>
        </button>
      </div>
    </div>
  )
}
